### ISSUE TITLE
Not working with current versions of jupyter notebook and lab

### ISSUE THREAD

**Issue by jdfekete** [john-guerra/navio_jupyter#16]
Hi John,
This notebook extension does not work any more with the latest notebook and jupyterlab.
Could you update it? A few things have changed in the toolchain.
Take a look at this article: https://blog.jupyter.org/packaging-for-jupyter-in-2022-c7be64c38926, it introduces the new toolchain with Hatch to build a jupyter extension that installs with pip install.

Thanks for your work!

**Comment by john-guerra** [comment]
Perfect, let me take a look

**Comment by john-guerra** [comment]
Quick update, I just spent a couple hours looking into this and couldn't update to the newer format yet. I'll keep on working on it.... cc @jdfekete

**Comment by john-guerra** [comment]
@jdfekete I have updated to anywidgets, seems to be working now, can you please check it out?
